// Mocks generated by Mockito 5.2.0 from annotations
// in motosapp/test/src/features/motorcycle/presentation/bloc/motorcycle_detail_bloc_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:motosapp/src/features/motorcycle/domain/entities/motorcycle_entity.dart'
    as _i7;
import 'package:motosapp/src/features/motorcycle/domain/repositories/motorcycle_repository.dart'
    as _i2;
import 'package:motosapp/src/features/motorcycle/domain/usecases/get_motorcycle_use_case.dart'
    as _i4;
import 'package:motosapp/src/shared/errors/failures.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeMotorcycleRepository_0 extends _i1.Fake
    implements _i2.MotorcycleRepository {}

class _FakeEither_1<L, R> extends _i1.Fake implements _i3.Either<L, R> {}

/// A class which mocks [GetMotorcycleUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetMotorcycleUseCase extends _i1.Mock
    implements _i4.GetMotorcycleUseCase {
  MockGetMotorcycleUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MotorcycleRepository get repository => (super.noSuchMethod(
      Invocation.getter(#repository),
      returnValue: _FakeMotorcycleRepository_0()) as _i2.MotorcycleRepository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.MotorcycleEntity>> call(
          String? params) =>
      (super.noSuchMethod(Invocation.method(#call, [params]),
              returnValue:
                  Future<_i3.Either<_i6.Failure, _i7.MotorcycleEntity>>.value(
                      _FakeEither_1<_i6.Failure, _i7.MotorcycleEntity>()))
          as _i5.Future<_i3.Either<_i6.Failure, _i7.MotorcycleEntity>>);
}
