// Mocks generated by Mockito 5.2.0 from annotations
// in motosapp/test/src/features/motorcycle/presentation/bloc/motorcycle_bloc_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:motosapp/src/features/motorcycle/domain/entities/motorcycle_entity.dart'
    as _i7;
import 'package:motosapp/src/features/motorcycle/domain/repositories/motorcycle_repository.dart'
    as _i2;
import 'package:motosapp/src/features/motorcycle/domain/usecases/delete_motorcycle_use_case.dart'
    as _i10;
import 'package:motosapp/src/features/motorcycle/domain/usecases/get_list_motorcycle_use_case.dart'
    as _i4;
import 'package:motosapp/src/features/motorcycle/domain/usecases/save_motorcycle_use_case.dart'
    as _i9;
import 'package:motosapp/src/shared/errors/failures.dart' as _i6;
import 'package:motosapp/src/shared/usescases/usecase.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeMotorcycleRepository_0 extends _i1.Fake
    implements _i2.MotorcycleRepository {}

class _FakeEither_1<L, R> extends _i1.Fake implements _i3.Either<L, R> {}

/// A class which mocks [GetListMotorcyclesUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetListMotorcyclesUseCase extends _i1.Mock
    implements _i4.GetListMotorcyclesUseCase {
  MockGetListMotorcyclesUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MotorcycleRepository get repository => (super.noSuchMethod(
      Invocation.getter(#repository),
      returnValue: _FakeMotorcycleRepository_0()) as _i2.MotorcycleRepository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i7.MotorcycleEntity>>> call(
          _i8.NoParams? params) =>
      (super.noSuchMethod(Invocation.method(#call, [params]),
          returnValue: Future<
                  _i3.Either<_i6.Failure, List<_i7.MotorcycleEntity>>>.value(
              _FakeEither_1<_i6.Failure, List<_i7.MotorcycleEntity>>())) as _i5
          .Future<_i3.Either<_i6.Failure, List<_i7.MotorcycleEntity>>>);
}

/// A class which mocks [SaveMotorcycleUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSaveMotorcycleUseCase extends _i1.Mock
    implements _i9.SaveMotorcycleUseCase {
  MockSaveMotorcycleUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MotorcycleRepository get repository => (super.noSuchMethod(
      Invocation.getter(#repository),
      returnValue: _FakeMotorcycleRepository_0()) as _i2.MotorcycleRepository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, void>> call(
          _i8.ParamsMotorcycle? params) =>
      (super.noSuchMethod(Invocation.method(#call, [params]),
              returnValue: Future<_i3.Either<_i6.Failure, void>>.value(
                  _FakeEither_1<_i6.Failure, void>()))
          as _i5.Future<_i3.Either<_i6.Failure, void>>);
}

/// A class which mocks [DeleteMotorcycleUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteMotorcycleUseCase extends _i1.Mock
    implements _i10.DeleteMotorcycleUseCase {
  MockDeleteMotorcycleUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MotorcycleRepository get repository => (super.noSuchMethod(
      Invocation.getter(#repository),
      returnValue: _FakeMotorcycleRepository_0()) as _i2.MotorcycleRepository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, void>> call(String? params) =>
      (super.noSuchMethod(Invocation.method(#call, [params]),
              returnValue: Future<_i3.Either<_i6.Failure, void>>.value(
                  _FakeEither_1<_i6.Failure, void>()))
          as _i5.Future<_i3.Either<_i6.Failure, void>>);
}
